name: "Release"
run-name: "Release - ${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to tag and release"
        required: true
      revision:
        description: "The package revision"
        default: "1"
      push-scm-changes:
        type: "boolean"
        description: "Should commits and tags be pushed?"
        required: false
        default: false

defaults:
  run:
    # Forces usage of Git Bash on Windows which makes the bash steps work.
    shell: "bash"

concurrency:
  group: "release"
  cancel-in-progress: false

env:
  NFPM_VERSION: "v2.46.3"
  AWS_DEFAULT_REGION: "eu-west-1"

jobs:
  tag:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
        with:
          ref: "${{ github.ref_name }}" # Pull latest revision!
          persist-credentials: true

      - name: "Setup Git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Setup graylog-project CLI"
        uses: "Graylog2/actions/project-cli@main"

      - name: "Setup Go environment"
        uses: "actions/setup-go@v6"
        with:
          go-version: "1.26"

      # Run build and test before we tag a release!
      - name: "Build binaries"
        run: "go tool task all"

      - name: "Run tests"
        run: "go tool task test"

      - name: "Set release version"
        env:
          RELEASE_VERSION: "${{ inputs.version }}"
          RELEASE_REVISION: "${{ inputs.revision }}"
        run: "go tool task version:set:release | tee version.env"

      - name: "Rotate changelog"
        run: |
          graylog-project changelog release:path "${{ inputs.version }}"

      - name: "Tag release"
        run: |
          git add -v version.env
          git commit -m "[release] Set version to ${{ inputs.version }}"
          git tag "${{ inputs.version }}"
          git show

      - name: "Set next SNAPSHOT version"
        run: "go tool task version:bump:snapshot:patch | tee version.env"

      - name: "Commit snapshot"
        run: |
          git add -v version.env
          git commit -m "[snapshot] Set version to $(go tool task version:get)"
          git show

      - name: "Push commits and tags"
        if: "inputs.push-scm-changes == true"
        run: |
          git push origin
          git push origin "${{ inputs.version }}"
